- include_tasks: mirror-user.yml

- import_role:
    name: httpd

- name: Adding vhost file
  template:
    src: 60_qa.conf.j2
    dest: /etc/httpd/conf.d/60_qa.conf
  notify:
    - restart_httpd
  tags:
    - acl

- name: Ensuring some selinux booleans are enabled
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: yes
  with_items:
    - httpd_enable_homedirs
    - httpd_read_user_content

- name: Script to gather mirror content
  template:
    src: rsync-master-full-qa.j2
    dest: "/home/{{ mirror_qa_local_user }}-scripts/rsync-master-full-qa"
    mode: 0755

- name: Cron job to rsync content from upstream node
  cron:
    name: "CentOS QA mirror rsync job"
    job: "/home/{{ mirror_qa_local_user }}-scripts/rsync-master-full-qa {{ mirror_qa_rsync_from }} > /dev/null 2>&1"
    minute: "*/12"
    user: "{{ mirror_qa_local_user }}"

- include_tasks: rsyncd.yml
  when: mirror_qa_rsyncd
  tags:
    - acl

- include_tasks: monitoring.yml  
